ZDOTDIR=$HOME/.config/zsh

# this line was probably added by cargo, but I did add `if` exprt so it doesn't
# trigger if you don't have cargo
if [ -e "$HOME/.cargo/env" ]
then
    . "$HOME/.cargo/env"
fi
