ZDOTDIR=$HOME/.config/zsh
NOCOR=1

# this line was probably added by cargo, but I did add `if` exprt so it doesn't
# trigger if you don't have cargo
if [ -r "$HOME/.cargo/env" ]
then
    . "$HOME/.cargo/env"
fi

# opam init, similar to rust's above
if [ -r "$HOME/.opam/opam-init/init.zsh" ]
then
    . "$HOME/.opam/opam-init/init.zsh" > /dev/null 2> /dev/null
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
