# download grml config if doesn't exist
if [ ! -f ~/.zsh/grml.zsh ]; then
    echo "grml configuration not found"
    echo "installing grml zsh configuration"
    curl -L https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc --create-dirs -o ~/.zsh/grml.zsh
fi

# load grml config
. ~/.zsh/grml.zsh

# prompts
autoload -U promptinit; promptinit

if git --version > /dev/null
then
    # two-line prompt with git integration
    # download if needed
    if [ ! -d ~/.zsh/agkozak-zsh-prompt ]; then
        git clone https://github.com/agkozak/agkozak-zsh-prompt \
            "$HOME/.zsh/agkozak-zsh-prompt"
    fi
    fpath+=($HOME/.zsh/agkozak-zsh-prompt)

    # options
    AGKOZAK_LEFT_PROMPT_ONLY=1
    AGKOZAK_PROMPT_DIRTRIM=0

    # setup
    # promptinit must go after `fpath` modification
    promptinit
    # actually choose the prompt
    prompt agkozak-zsh-prompt
else
    # fallback, comes with zsh by default
    prompt adam2
fi

# "main" function, because I do want my local variables to stay local
function () {
    # some variables
    local DOTFILES="$HOME/.config/dotfiles"
    local SHELL_RC="$HOME/.config/zsh/.zshrc"
    local VIM_RC="$HOME/.config/nvim/init.lua"
    local WORK="$HOME/Workspace"
    export EDITOR="nvim"

    # better path
    export PATH=$HOME/.local/bin:$PATH

    # aliases
    alias cddot="cd $DOTFILES"
    alias cdwork="cd $WORK"
    alias upd="source $SHELL_RC"
    alias edsh="$EDITOR $SHELL_RC"
    alias edvim="$EDITOR $VIM_RC"
}
