# Download grml config if doesn't exist

if [ ! -f ~/.zsh/grml.zsh ]; then
    echo "grml configuration not found"
    echo "installing grml zsh configuration"
    curl -L https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc --create-dirs -o ~/.zsh/grml.zsh
fi

# load grml config
. ~/.zsh/grml.zsh

# "main" function, because I do want my local variables to stay local
function () {
    # some variables
    local DOTFILES="$HOME/.config/dotfiles"
    local SHELL_RC="$HOME/.zshrc"
    local VIM_RC="$HOME/.config/nvim/init.lua"
    export EDITOR="nvim"

    # better path
    export PATH=$HOME/.local/bin:$PATH

    # aliases
    alias cddot="cd $DOTFILES"
    alias upd="source $SHELL_RC"
    alias edsh="$EDITOR $SHELL_RC"
    alias edvim="$EDITOR $VIM_RC"
}
