[general]
import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[font]
size = 14.0

[terminal.shell]
args = ["--login", "-c", "tmux"]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"
